title: "Dane Wesolko"
description: "Product Designer with a passion for Healthcare and Life Sciences."
url: "https://danewesolko.com"

# Site owner
author:
  name: "Dane Wesolko"
  uri: &uri "https://danewesolko.com/about"
  url: *uri
  bio: "Product Designer with a passion for Healthcare and Life Sciences."

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  - authors

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

favicon:
  source: favicon.svg
  path: /assets/img

permalink: /:title
